import type { MetadataRoute } from "next";

const SITE_URL = "https://www.lokrainfra.in";

const PUBLIC_ROUTES = [
  "",
  "/about",
  "/services",
  "/packages",
  "/projects",
  "/process",
  "/affordable-construction-packages-chennai",
  "/budget-home-construction-chennai",
  "/waterproofing-construction-package-chennai",
  "/quality-checked-structure-package-chennai",
  "/home-construction-chennai",
  "/building-contractors-chennai",
  "/civil-contractors-chennai",
  "/commercial-construction-chennai",
  "/villa-construction-chennai",
  "/renovation-contractors-chennai",
  "/builders-in-omr-chennai",
  "/builders-in-porur-chennai",
  "/builders-in-tambaram-chennai",
  "/builders-in-velachery-chennai",
  "/builders-in-sholinganallur-chennai",
  "/builders-along-gst-road-chennai",
  "/builders-in-adyar-chennai",
  "/builders-in-besant-nagar-chennai",
  "/builders-in-kolathur-chennai",
  "/builders-in-mylapore-chennai",
  "/builders-in-guduvanchery-chennai",
  "/chennai-areas",
  "/builders-in-alwarpet-chennai",
  "/builders-in-anna-nagar-chennai",
  "/builders-in-nungambakkam-chennai",
  "/builders-in-ra-puram-chennai",
  "/builders-in-t-nagar-chennai",
  "/builders-in-choolaimedu-chennai",
  "/builders-in-guindy-chennai",
  "/builders-in-kandanchavadi-chennai",
  "/builders-in-kottivakkam-chennai",
  "/builders-in-madipakkam-chennai",
  "/builders-in-medavakkam-chennai",
  "/builders-in-nanganallur-chennai",
  "/builders-in-palavakkam-chennai",
  "/builders-in-pallikaranai-chennai",
  "/builders-in-perungudi-chennai",
  "/builders-in-thiruvanmiyur-chennai",
  "/builders-in-thoraipakkam-chennai",
  "/builders-in-manapakkam-chennai",
  "/builders-in-ambattur-chennai",
  "/builders-in-avadi-chennai",
  "/builders-in-iyyappanthangal-chennai",
  "/builders-in-kattupakkam-chennai",
  "/builders-in-kizhalathur-chennai",
  "/builders-in-koyambedu-chennai",
  "/builders-in-maduravoyal-chennai",
  "/builders-in-mogappair-chennai",
  "/builders-in-poonamallee-chennai",
  "/builders-in-ramapuram-chennai",
  "/builders-in-valasaravakkam-chennai",
  "/builders-in-vanagaram-chennai",
  "/builders-in-ennore-chennai",
  "/builders-in-madhavaram-chennai",
  "/builders-in-manali-chennai",
  "/builders-in-perambur-chennai",
  "/builders-in-royapuram-chennai",
  "/builders-in-tondiarpet-chennai",
  "/builders-in-vyasarpadi-chennai",
  "/builders-in-chromepet-chennai",
  "/builders-in-kelambakkam-chennai",
  "/builders-in-kundrathur-chennai",
  "/builders-in-mangadu-chennai",
  "/builders-in-navallur-chennai",
  "/builders-in-omalur-chennai",
  "/builders-in-padur-chennai",
  "/builders-in-perungalathur-chennai",
  "/builders-in-singaperumal-koil-chennai",
  "/builders-in-sriperumbudur-chennai",
  "/builders-in-urapakkam-chennai",
  "/builders-in-vandalur-chennai",
  "/jv-partnerships",
  "/contact",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  return PUBLIC_ROUTES.map((route) => ({
    url: `${SITE_URL}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : 0.7,
  }));
}